### ISSUE TITLE
Nesting directories/files

### ISSUE THREAD

**Issue by sgarbesi** [jarradseers/express-load#34]
I have a folder/file structure like this:

```
controller/
  app/
    token.js
    token/
      access.js
      authorization.js
      refresh.js
```

It would be nice to be able to extend off of `app` allowing to have multiple levels. I can't seem to get it working and didn't see anything in the documentation explaining this.

**Example:**

```javascript
controller.app.token();
controller.app.token.access(); // This doesn't work.
```

**Comment by caio-ribeiro-pereira** [comment]
I'm having the same trouble...

**Comment by sgarbesi** [comment]
@caio-ribeiro-pereira As a hacky solution I wound up just adding a loader function to each of my top level classes/functions. Hacky, but it works.

So token.js would have it's own express loader and load up the token.access function.

**Comment by sgarbesi** [comment]
@caio-ribeiro-pereira Try my pull request.
